import MetaLayout from "components/meta-layout";
import { SessionProvider } from "./(home)/SessionProvider";
import SWRProvider from "./(home)/SWRProvider";
import UserContext from "./(home)/UserContext";

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <head>
        <title>Aces Next Prisma MongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <SWRProvider>
          <SessionProvider>
            <UserContext />
            <hr />
            {/* <MetaLayout leftContent={<div>LEFT</div>}>{children}</MetaLayout> */}
            {children}
          </SessionProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
