import { SessionProvider } from "./(home)/SessionProvider";
import SWRProvider from "./(home)/SWRProvider";
import UserContext from "./(home)/UserContext";
import { cookies } from "next/headers";

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  // Able to access to cookie
  // but no way to unseal the data
  const v = cookies().get("aces/next/iron-session")?.value;
  console.log(v?.length);

  return (
    <html lang="en">
      <head>
        <title>Aces Next Prisma MongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <SWRProvider>
          <SessionProvider>
            <UserContext />
            <hr />
            {children}
          </SessionProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
